### ISSUE TITLE
read_pk_rep()  'Selectivity_parameters' repeated for each survey but only returning values for survey 1

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [afsc-assessments/GOApollock#1]
```
> rep[names(rep)[which(grepl('Selectivity_parameters', names(rep)))]]

$Selectivity_parameters
[1] 0.61416 9.60821

$Selectivity_parameters
[1] 0.61416 9.60821

$Selectivity_parameters
[1] 0.61416 9.60821

$Selectivity_parameters
[1] 0.61416 9.60821
```

**Comment by Cole-Monnahan-NOAA** [comment]
This was caused by non-unique names in the report file. The model was updated to be unique by survey. See [this commit](https://github.com/afsc-assessments/GOApollock/commit/d77cc13b6feb22c32efe626e9c02a30b0acbd770#diff-43a09557815db8bf994329b364ca7abe28e037035818bd23807bd3c4900ed39dR1232).
